FROM zhcoder-docker-registry.com:8000/official/library/debian:bullseye-slim

RUN echo "Types: deb" > /etc/apt/sources.list.d/tuna.sources && \
    echo "URIs: https://mirrors.tuna.tsinghua.edu.cn/debian" >> /etc/apt/sources.list.d/tuna.sources && \
    echo "Suites: bookworm bookworm-updates bookworm-backports" >> /etc/apt/sources.list.d/tuna.sources && \
    echo "Components: main contrib non-free non-free-firmware" >> /etc/apt/sources.list.d/tuna.sources && \
    echo "Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg" >> /etc/apt/sources.list.d/tuna.sources && \
    echo "" >> /etc/apt/sources.list.d/tuna.sources && \
    echo "Types: deb" >> /etc/apt/sources.list.d/tuna.sources && \
    echo "URIs: https://mirrors.tuna.tsinghua.edu.cn/debian-security" >> /etc/apt/sources.list.d/tuna.sources && \
    echo "Suites: bookworm-security" >> /etc/apt/sources.list.d/tuna.sources && \
    echo "Components: main contrib non-free non-free-firmware" >> /etc/apt/sources.list.d/tuna.sources && \
    echo "Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg" >> /etc/apt/sources.list.d/tuna.sources

RUN apt-get update && \
    apt-get install -y cmake ninja-build && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*