FROM mcr.microsoft.com/dotnet/sdk:9.0
RUN echo "Types: deb" > /etc/apt/sources.list.d/tuna.sources && \
    echo "URIs: https://mirrors.tuna.tsinghua.edu.cn/debian" >> /etc/apt/sources.list.d/tuna.sources && \
    echo "Suites: bookworm bookworm-updates bookworm-backports" >> /etc/apt/sources.list.d/tuna.sources && \
    echo "Components: main contrib non-free non-free-firmware" >> /etc/apt/sources.list.d/tuna.sources && \
    echo "Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg" >> /etc/apt/sources.list.d/tuna.sources && \
    echo "" >> /etc/apt/sources.list.d/tuna.sources && \
    echo "Types: deb" >> /etc/apt/sources.list.d/tuna.sources && \
    echo "URIs: https://mirrors.tuna.tsinghua.edu.cn/debian-security" >> /etc/apt/sources.list.d/tuna.sources && \
    echo "Suites: bookworm-security" >> /etc/apt/sources.list.d/tuna.sources && \
    echo "Components: main contrib non-free non-free-firmware" >> /etc/apt/sources.list.d/tuna.sources && \
    echo "Signed-By: /usr/share/keyrings/debian-archive-keyring.gpg" >> /etc/apt/sources.list.d/tuna.sources
# 安装系统依赖
RUN apt-get update && apt-get upgrade -y 
# 设置工作目录
WORKDIR /workspace

RUN apt update && \
    apt upgrade -y
RUN /usr/bin/apt install -y \
    curl \
    wget \
    unzip \
    zip \
    tree \
    htop \
    iputils-ping \
    nano \
    telnet\
    lsof\
    net-tools\
    jq tree lsof \
    && rm -rf /var/lib/apt/lists/*

# 创建非root用户
RUN useradd -m -s /bin/bash developer && \
    chown -R developer:developer /workspace
USER developer

# 设置环境变量
ENV DOTNET_CLI_TELEMETRY_OPTOUT=1
ENV ASPNETCORE_ENVIRONMENT=Development
COPY ./nuget.config /home/developer/.nuget/nuget.config
CMD ["tail", "-f", "/dev/null"]
