FROM mcr.microsoft.com/dotnet/sdk:9.0

# 设置工作目录
WORKDIR /workspace

# 创建非root用户
RUN useradd -m -s /bin/bash developer && \
    chown -R developer:developer /workspace
USER developer

# 设置环境变量
ENV DOTNET_CLI_TELEMETRY_OPTOUT=1
ENV ASPNETCORE_ENVIRONMENT=Development
COPY ./nuget.config /home/developer/.nuget/nuget.config
CMD ["tail", "-f", "/dev/null"]
