FROM mcr.microsoft.com/dotnet/sdk:3.1

# 设置工作目录
WORKDIR /workspace
RUN sed -i 's|deb.debian.org|archive.debian.org|g' /etc/apt/sources.list && \
    sed -i 's|security.debian.org|archive.debian.org/debian-security|g' /etc/apt/sources.list && \
    apt update && \
    apt upgrade -y
RUN /usr/bin/apt install -y \
    curl \
    wget \
    unzip \
    zip \
    tree \
    htop \
    iputils-ping \
    && rm -rf /var/lib/apt/lists/*



# 设置环境变量
ENV DOTNET_CLI_TELEMETRY_OPTOUT=1
ENV ASPNETCORE_ENVIRONMENT=Development
COPY ./nuget.config /root/.nuget/nuget.config
CMD ["tail", "-f", "/dev/null"]
