version: '3.8'
services:
  dotnet-dev:
    image: zhcoder-docker-registry.com:8000/dev-env/node-dev-16:1.0
    container_name: ${CONTAINER_NAME:-dotnet-dev}
    volumes:
      - ${workspace}:/workspace
      - nuget-packages:/home/developer/.nuget/packages
    working_dir: /workspace
    ports:
      - "${APP_PORT:-5001:5660}"
    command: tail -f /dev/null
    networks:
      - dev-network

volumes:
  nuget-packages:

networks:
  dev-network:
    driver: bridge
