version: '3.8'

services:
  python-dev:
    build: .
    container_name: ${CONTAINER_NAME:-python-dev}
    volumes:
      - ${SOURCE_CODE_PATH}:/workspace
      - python-packages:/usr/local/lib/python3.11/site-packages
    working_dir: /workspace
    ports:
      - "${APP_PORT:-5000}:5000"
      - "8000:8000"
    environment:
      - PYTHONPATH=/workspace
      - FLASK_ENV=development
    command: tail -f /dev/null
    networks:
      - dev-network

volumes:
  python-packages:

networks:
  dev-network:
    driver: bridge
