FROM mcr.microsoft.com/dotnet/sdk:2.1

# 设置工作目录
WORKDIR /workspace
# 配置 Debian stretch 源
RUN echo "deb http://archive.debian.org/debian stretch main" > /etc/apt/sources.list && \
    echo "deb http://archive.debian.org/debian stretch-backports main" >> /etc/apt/sources.list && \
    apt-get update && \
    apt-get upgrade -y
RUN /usr/bin/apt-get install -y \
    curl \
    wget \
    unzip \
    zip \
    tree \
    htop \
    iputils-ping \
    && rm -rf /var/lib/apt/lists/*



# 设置环境变量
ENV DOTNET_CLI_TELEMETRY_OPTOUT=1
ENV ASPNETCORE_ENVIRONMENT=Development
COPY ./nuget.config /root/.nuget/nuget.config
CMD ["tail", "-f", "/dev/null"]
